### ISSUE TITLE
Add Documentation to the README

### ISSUE THREAD

**Issue by 7hunderbird** [starkandwayne/cf-deployment#1]
The `cf-deployment` template needs a README that explains what all of the `(( param ... ))` calls are for, and what they should be set to.

**Comment by geofffranks** [comment]
If the param calls are not helpful enough, they should be updated. I hesitate to add descriptions to a readme, since updates will then mean changing the information in both the param calls and the readme.

**Comment by 7hunderbird** [comment]
Right, if the code changes then the README has been outdated too... good point.  I think instead it would be better to have good documentation and training around how `(( param ... ))` works in `genesis`, how it's used and ways to "solve for x".
