### ISSUE TITLE
certstrap dep

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/cf-deployment#3]
does [this](https://github.com/starkandwayne/cf-deployment/blob/master/.genesis_deps#L3) refer to https://github.com/square/certstrap?

If so it means we need golang installed on the jumpbox we are using this template from. Perhaps we could add golang to https://github.com/starkandwayne/jumpbox?
Also this .genesis_deps thing always breaks the genesis pipeline when adding deps that aren't contained in the starkandwayne/concourse image. We need to think of a way to differentiate between install deps vs pipeline deps.

**Comment by geofffranks** [comment]
It is that utility. Feel free to add to the jumpbox script and boshrelease. I was thinking of an env var to skip dependency checking under concourse, or other circumstances.

**Comment by frodenas** [comment]
@bodymindarts: FYI, jumpbox now install certstrap: https://github.com/starkandwayne/jumpbox/pull/7

**Comment by geofffranks** [comment]
Closing this in favor of a genesis ticket to separate hook deps from all-the-time deps

**Comment by geofffranks** [comment]
see https://github.com/starkandwayne/genesis/issues/61
