### ISSUE TITLE
Default setting for uaadb and ccdb

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/cf-deployment#6]
The default scheme for uaadb and ccdb is MySql, in codex we are using PostgreSql, what do you think we remove this default setting , then in codex we add that we need to configure uaadb and ccdb scheme? 

This will save us some time in the scenario that customer not using MySql (default setting now), we have to deploy CF, then uaa vm failed, then we debug and find out wrong db scheme is configured and deploy it again

**Comment by jhunt** [comment]
sounds good.
